"""Build the Phase 3 Advanced ML Jupyter notebook."""
import json
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
nb_path = PROJECT / "notebooks" / "Phase3_Advanced_ML.ipynb"

cells = []

def md(source):
    cells.append({"cell_type": "markdown", "metadata": {}, "source": source})

def code(source):
    cells.append({"cell_type": "code", "execution_count": None,
                  "metadata": {}, "outputs": [], "source": source})


# ============================================================
# TITLE & INTRO
# ============================================================
md([
    "# Phase 3 — Advanced ML Architecture & Fine-Tuning\n",
    "## LoRA Fine-Tuning of Open-Weight LLMs for Policy Stance Regression\n",
    "\n",
    "This notebook implements the core technical contribution:\n",
    "\n",
    "**Milestones:**\n",
    "- M4: Infrastructure Setup & Experiment Tracking\n",
    "- M5: LoRA Fine-Tuning (Regression on High-Frequency Market Labels)\n",
    "- M6: Embedding Extraction, Latent Stance Index & Interpretability\n",
    "\n",
    "**Architecture:** Llama-3-8B-Instruct or Mistral-7B-Instruct-v0.3 + LoRA adapter + linear regression head\n",
    "\n",
    "**Objective:** Predict continuous Δy₂ (basis-point yield change) from text chunks\n",
    "\n",
    "---"
])

# ============================================================
# IMPORTS & SETUP
# ============================================================
code([
    "import sys\n",
    "import os\n",
    "import logging\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from scipy import stats\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "from transformers import (\n",
    "    AutoTokenizer,\n",
    "    AutoModelForCausalLM,\n",
    "    BitsAndBytesConfig,\n",
    "    TrainingArguments,\n",
    "    Trainer,\n",
    ")\n",
    "from peft import LoraConfig, get_peft_model, TaskType, PeftModel\n",
    "from tqdm.notebook import tqdm\n",
    "\n",
    "PROJECT_ROOT = Path('.').resolve().parent\n",
    "sys.path.insert(0, str(PROJECT_ROOT))\n",
    "\n",
    "# Reproducibility\n",
    "SEED = 42\n",
    "np.random.seed(SEED)\n",
    "torch.manual_seed(SEED)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed_all(SEED)\n",
    "\n",
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "print(f'Device: {device}')\n",
    "if device == 'cuda':\n",
    "    print(f'GPU: {torch.cuda.get_device_name(0)}')\n",
    "    print(f'VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB')\n",
    "print(f'PyTorch: {torch.__version__}')\n",
    "print(f'Project: {PROJECT_ROOT}')\n",
])


# ============================================================
# M4: INFRASTRUCTURE & DATA SPLIT
# ============================================================
md([
    "---\n",
    "## Milestone 4: Infrastructure Setup & Temporal Split\n",
    "\n",
    "**Critical:** Strict temporal train/validation/test split.\n",
    "- Train: 2005–2018\n",
    "- Validation: 2019–2020\n",
    "- Test: 2021–present (touched exactly ONCE at final reporting)\n",
])

code([
    "# Load labeled chunks (requires Phase 1 complete + market data)\n",
    "labeled_path = PROJECT_ROOT / 'data' / 'processed' / 'chunk_registry_labeled.parquet'\n",
    "chunks_path = PROJECT_ROOT / 'data' / 'processed' / 'chunk_registry_window.parquet'\n",
    "\n",
    "if labeled_path.exists():\n",
    "    chunks = pd.read_parquet(labeled_path)\n",
    "    print(f'Loaded labeled chunks: {len(chunks):,}')\n",
    "else:\n",
    "    chunks = pd.read_parquet(chunks_path)\n",
    "    print(f'Loaded chunks (unlabeled): {len(chunks):,}')\n",
    "    print('WARNING: No market labels yet. Model will train once labels are available.')\n",
    "    print('For now, this notebook defines the full pipeline structure.')\n",
    "\n",
    "chunks['date'] = pd.to_datetime(chunks['date'])\n",
    "chunks['year'] = chunks['date'].dt.year\n",
    "print(f'Date range: {chunks[\"date\"].min().date()} to {chunks[\"date\"].max().date()}')\n",
])

code([
    "# Temporal split — LOCKED, do not modify post-hoc\n",
    "TRAIN_END = '2018-12-31'\n",
    "VAL_END = '2020-12-31'\n",
    "\n",
    "train_mask = chunks['date'] <= TRAIN_END\n",
    "val_mask = (chunks['date'] > TRAIN_END) & (chunks['date'] <= VAL_END)\n",
    "test_mask = chunks['date'] > VAL_END\n",
    "\n",
    "train_chunks = chunks[train_mask].copy()\n",
    "val_chunks = chunks[val_mask].copy()\n",
    "test_chunks = chunks[test_mask].copy()\n",
    "\n",
    "print(f'Temporal Split:')\n",
    "print(f'  Train (2005-2018):  {len(train_chunks):,} chunks')\n",
    "print(f'  Val   (2019-2020):  {len(val_chunks):,} chunks')\n",
    "print(f'  Test  (2021+):      {len(test_chunks):,} chunks')\n",
    "print(f'\\nTrain central banks: {train_chunks[\"central_bank\"].nunique()}')\n",
    "print(f'Val central banks:   {val_chunks[\"central_bank\"].nunique()}')\n",
    "print(f'Test central banks:  {test_chunks[\"central_bank\"].nunique()}')\n",
])

code([
    "# Experiment tracking setup\n",
    "try:\n",
    "    import wandb\n",
    "    WANDB_AVAILABLE = True\n",
    "    print('W&B available for experiment tracking')\n",
    "except ImportError:\n",
    "    WANDB_AVAILABLE = False\n",
    "\n",
    "try:\n",
    "    import mlflow\n",
    "    MLFLOW_AVAILABLE = True\n",
    "    mlflow.set_tracking_uri(str(PROJECT_ROOT / 'mlruns'))\n",
    "    mlflow.set_experiment('latent-policy-stance')\n",
    "    print('MLflow available for experiment tracking')\n",
    "except ImportError:\n",
    "    MLFLOW_AVAILABLE = False\n",
    "\n",
    "if not WANDB_AVAILABLE and not MLFLOW_AVAILABLE:\n",
    "    print('No experiment tracking configured. Results will be saved locally.')\n",
])


# ============================================================
# M5: LORA FINE-TUNING
# ============================================================
md([
    "---\n",
    "## Milestone 5: LoRA Fine-Tuning\n",
    "\n",
    "**Architecture:**\n",
    "- Base: Llama-3-8B-Instruct or Mistral-7B-Instruct-v0.3\n",
    "- LoRA: rank r ∈ {8, 16, 32}, alpha = 2r, dropout = 0.05\n",
    "- Target modules: q_proj, v_proj, k_proj, o_proj\n",
    "- Regression head: Linear(d_model → 1)\n",
    "- Loss: MSE\n",
    "- Optimizer: AdamW (lr=1e-4, weight_decay=0.01)\n",
    "- Schedule: cosine with warmup\n",
    "\n",
    "**Key safeguards:**\n",
    "- Null model sanity check (shuffled labels → r ≈ 0)\n",
    "- Early stopping (patience = 3 epochs on val MSE)\n",
    "- Train/val MSE gap monitoring (gap > 2x signals overfitting)\n",
])

code([
    "# Dataset class for regression\n",
    "class PolicyStanceDataset(Dataset):\n",
    "    \"\"\"Dataset for policy stance regression.\"\"\"\n",
    "    \n",
    "    def __init__(self, texts, labels, tokenizer, max_length=512):\n",
    "        self.texts = texts\n",
    "        self.labels = labels\n",
    "        self.tokenizer = tokenizer\n",
    "        self.max_length = max_length\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.texts)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        text = self.texts[idx]\n",
    "        label = self.labels[idx]\n",
    "        \n",
    "        encoding = self.tokenizer(\n",
    "            text,\n",
    "            truncation=True,\n",
    "            max_length=self.max_length,\n",
    "            padding='max_length',\n",
    "            return_tensors='pt',\n",
    "        )\n",
    "        \n",
    "        return {\n",
    "            'input_ids': encoding['input_ids'].squeeze(),\n",
    "            'attention_mask': encoding['attention_mask'].squeeze(),\n",
    "            'labels': torch.tensor(label, dtype=torch.float32),\n",
    "        }\n",
    "\n",
    "\n",
    "print('PolicyStanceDataset class defined.')\n",
])

code([
    "# Model wrapper: base LLM + LoRA + regression head\n",
    "class PolicyStanceRegressor(nn.Module):\n",
    "    \"\"\"LLM with LoRA adapter and linear regression head.\"\"\"\n",
    "    \n",
    "    def __init__(self, base_model, hidden_size):\n",
    "        super().__init__()\n",
    "        self.base_model = base_model\n",
    "        self.regression_head = nn.Linear(hidden_size, 1)\n",
    "        self.dropout = nn.Dropout(0.1)\n",
    "    \n",
    "    def forward(self, input_ids, attention_mask, labels=None):\n",
    "        # Get hidden states from base model\n",
    "        outputs = self.base_model(\n",
    "            input_ids=input_ids,\n",
    "            attention_mask=attention_mask,\n",
    "            output_hidden_states=True,\n",
    "        )\n",
    "        \n",
    "        # Use last hidden state, mean-pool over non-padded tokens\n",
    "        hidden_states = outputs.hidden_states[-1]  # (batch, seq_len, hidden)\n",
    "        mask_expanded = attention_mask.unsqueeze(-1).float()\n",
    "        sum_hidden = (hidden_states * mask_expanded).sum(dim=1)\n",
    "        count = mask_expanded.sum(dim=1)\n",
    "        mean_pooled = sum_hidden / count  # (batch, hidden)\n",
    "        \n",
    "        # Regression\n",
    "        pooled = self.dropout(mean_pooled)\n",
    "        prediction = self.regression_head(pooled).squeeze(-1)  # (batch,)\n",
    "        \n",
    "        loss = None\n",
    "        if labels is not None:\n",
    "            loss_fn = nn.MSELoss()\n",
    "            loss = loss_fn(prediction, labels)\n",
    "        \n",
    "        return {'loss': loss, 'prediction': prediction}\n",
    "\n",
    "\n",
    "print('PolicyStanceRegressor class defined.')\n",
])

code([
    "# Configuration\n",
    "MODEL_NAME = 'mistralai/Mistral-7B-Instruct-v0.3'  # or 'meta-llama/Meta-Llama-3-8B-Instruct'\n",
    "LORA_RANK = 16\n",
    "LORA_ALPHA = 32  # 2 * rank\n",
    "LORA_DROPOUT = 0.05\n",
    "MAX_LENGTH = 512\n",
    "BATCH_SIZE = 4  # Adjust based on VRAM\n",
    "LEARNING_RATE = 1e-4\n",
    "WEIGHT_DECAY = 0.01\n",
    "NUM_EPOCHS = 10\n",
    "PATIENCE = 3  # Early stopping\n",
    "GRAD_CLIP = 1.0\n",
    "\n",
    "print(f'Configuration:')\n",
    "print(f'  Model: {MODEL_NAME}')\n",
    "print(f'  LoRA rank: {LORA_RANK}, alpha: {LORA_ALPHA}')\n",
    "print(f'  Batch size: {BATCH_SIZE}')\n",
    "print(f'  Learning rate: {LEARNING_RATE}')\n",
    "print(f'  Epochs: {NUM_EPOCHS} (early stop patience: {PATIENCE})')\n",
])


code([
    "# Load base model with quantization (4-bit for memory efficiency)\n",
    "print(f'Loading {MODEL_NAME}...')\n",
    "print('(This requires ~16GB VRAM for 4-bit or ~6GB for 8-bit)')\n",
    "\n",
    "# Quantization config\n",
    "bnb_config = BitsAndBytesConfig(\n",
    "    load_in_4bit=True,\n",
    "    bnb_4bit_quant_type='nf4',\n",
    "    bnb_4bit_compute_dtype=torch.float16,\n",
    "    bnb_4bit_use_double_quant=True,\n",
    ")\n",
    "\n",
    "# Load tokenizer\n",
    "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n",
    "if tokenizer.pad_token is None:\n",
    "    tokenizer.pad_token = tokenizer.eos_token\n",
    "\n",
    "# Load model\n",
    "base_model = AutoModelForCausalLM.from_pretrained(\n",
    "    MODEL_NAME,\n",
    "    quantization_config=bnb_config,\n",
    "    device_map='auto',\n",
    "    trust_remote_code=True,\n",
    ")\n",
    "base_model.config.use_cache = False\n",
    "\n",
    "print(f'Model loaded. Parameters: {sum(p.numel() for p in base_model.parameters()) / 1e9:.2f}B')\n",
])

code([
    "# Apply LoRA\n",
    "lora_config = LoraConfig(\n",
    "    r=LORA_RANK,\n",
    "    lora_alpha=LORA_ALPHA,\n",
    "    lora_dropout=LORA_DROPOUT,\n",
    "    target_modules=['q_proj', 'v_proj', 'k_proj', 'o_proj'],\n",
    "    bias='none',\n",
    "    task_type=TaskType.CAUSAL_LM,\n",
    ")\n",
    "\n",
    "peft_model = get_peft_model(base_model, lora_config)\n",
    "\n",
    "trainable_params = sum(p.numel() for p in peft_model.parameters() if p.requires_grad)\n",
    "total_params = sum(p.numel() for p in peft_model.parameters())\n",
    "print(f'LoRA applied:')\n",
    "print(f'  Trainable parameters: {trainable_params:,} ({trainable_params/total_params*100:.2f}%)')\n",
    "print(f'  Total parameters: {total_params:,}')\n",
    "print(f'  Reduction factor: {total_params / trainable_params:.0f}x')\n",
])

code([
    "# Build the full regression model\n",
    "hidden_size = base_model.config.hidden_size  # 4096 for Mistral/Llama\n",
    "model = PolicyStanceRegressor(peft_model, hidden_size)\n",
    "model = model.to(device)\n",
    "\n",
    "print(f'PolicyStanceRegressor ready.')\n",
    "print(f'  Hidden size: {hidden_size}')\n",
    "print(f'  Regression head: Linear({hidden_size} -> 1)')\n",
])

code([
    "# Prepare datasets\n",
    "HAS_LABELS = 'delta_yield_2y_bp' in chunks.columns and chunks['delta_yield_2y_bp'].notna().any()\n",
    "\n",
    "if HAS_LABELS:\n",
    "    # Filter to labeled data only\n",
    "    train_data = train_chunks[train_chunks['delta_yield_2y_bp'].notna()]\n",
    "    val_data = val_chunks[val_chunks['delta_yield_2y_bp'].notna()]\n",
    "    \n",
    "    train_dataset = PolicyStanceDataset(\n",
    "        texts=train_data['text'].tolist(),\n",
    "        labels=train_data['delta_yield_2y_bp'].values,\n",
    "        tokenizer=tokenizer,\n",
    "        max_length=MAX_LENGTH,\n",
    "    )\n",
    "    val_dataset = PolicyStanceDataset(\n",
    "        texts=val_data['text'].tolist(),\n",
    "        labels=val_data['delta_yield_2y_bp'].values,\n",
    "        tokenizer=tokenizer,\n",
    "        max_length=MAX_LENGTH,\n",
    "    )\n",
    "    \n",
    "    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)\n",
    "    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)\n",
    "    \n",
    "    print(f'Datasets ready:')\n",
    "    print(f'  Train: {len(train_dataset)} samples')\n",
    "    print(f'  Val: {len(val_dataset)} samples')\n",
    "else:\n",
    "    print('No labels available. Pipeline is defined but cannot train yet.')\n",
    "    print('Provide tick data and re-run Phase 1 label construction first.')\n",
])


code([
    "# Training loop with early stopping\n",
    "def train_model(model, train_loader, val_loader, num_epochs, lr, patience, grad_clip):\n",
    "    \"\"\"Train with early stopping on validation MSE.\"\"\"\n",
    "    optimizer = torch.optim.AdamW(\n",
    "        model.parameters(), lr=lr, weight_decay=WEIGHT_DECAY\n",
    "    )\n",
    "    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(\n",
    "        optimizer, T_max=num_epochs\n",
    "    )\n",
    "    \n",
    "    best_val_loss = float('inf')\n",
    "    patience_counter = 0\n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_r': []}\n",
    "    \n",
    "    for epoch in range(num_epochs):\n",
    "        # Train\n",
    "        model.train()\n",
    "        train_losses = []\n",
    "        for batch in tqdm(train_loader, desc=f'Epoch {epoch+1}/{num_epochs}'):\n",
    "            batch = {k: v.to(device) for k, v in batch.items()}\n",
    "            outputs = model(\n",
    "                input_ids=batch['input_ids'],\n",
    "                attention_mask=batch['attention_mask'],\n",
    "                labels=batch['labels'],\n",
    "            )\n",
    "            loss = outputs['loss']\n",
    "            loss.backward()\n",
    "            torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)\n",
    "            optimizer.step()\n",
    "            optimizer.zero_grad()\n",
    "            train_losses.append(loss.item())\n",
    "        \n",
    "        scheduler.step()\n",
    "        avg_train_loss = np.mean(train_losses)\n",
    "        \n",
    "        # Validate\n",
    "        model.eval()\n",
    "        val_losses = []\n",
    "        val_preds = []\n",
    "        val_labels = []\n",
    "        with torch.no_grad():\n",
    "            for batch in val_loader:\n",
    "                batch = {k: v.to(device) for k, v in batch.items()}\n",
    "                outputs = model(\n",
    "                    input_ids=batch['input_ids'],\n",
    "                    attention_mask=batch['attention_mask'],\n",
    "                    labels=batch['labels'],\n",
    "                )\n",
    "                val_losses.append(outputs['loss'].item())\n",
    "                val_preds.extend(outputs['prediction'].cpu().numpy())\n",
    "                val_labels.extend(batch['labels'].cpu().numpy())\n",
    "        \n",
    "        avg_val_loss = np.mean(val_losses)\n",
    "        val_r = stats.pearsonr(val_preds, val_labels)[0]\n",
    "        \n",
    "        history['train_loss'].append(avg_train_loss)\n",
    "        history['val_loss'].append(avg_val_loss)\n",
    "        history['val_r'].append(val_r)\n",
    "        \n",
    "        print(f'  Epoch {epoch+1}: train_loss={avg_train_loss:.4f}, '\n",
    "              f'val_loss={avg_val_loss:.4f}, val_r={val_r:.4f}')\n",
    "        \n",
    "        # Early stopping\n",
    "        if avg_val_loss < best_val_loss:\n",
    "            best_val_loss = avg_val_loss\n",
    "            patience_counter = 0\n",
    "            # Save best checkpoint\n",
    "            ckpt_dir = PROJECT_ROOT / 'models' / 'best_checkpoint'\n",
    "            ckpt_dir.mkdir(parents=True, exist_ok=True)\n",
    "            torch.save(model.state_dict(), ckpt_dir / 'model.pt')\n",
    "            print(f'  -> Best model saved (val_loss={best_val_loss:.4f})')\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            if patience_counter >= patience:\n",
    "                print(f'  Early stopping at epoch {epoch+1}')\n",
    "                break\n",
    "        \n",
    "        # Overfitting check\n",
    "        if avg_val_loss > 2 * avg_train_loss:\n",
    "            print(f'  WARNING: val_loss > 2x train_loss — possible overfitting!')\n",
    "    \n",
    "    return history\n",
    "\n",
    "\n",
    "# Run training (only if labels available)\n",
    "if HAS_LABELS:\n",
    "    print('Starting training...')\n",
    "    history = train_model(\n",
    "        model, train_loader, val_loader,\n",
    "        num_epochs=NUM_EPOCHS, lr=LEARNING_RATE,\n",
    "        patience=PATIENCE, grad_clip=GRAD_CLIP,\n",
    "    )\n",
    "else:\n",
    "    print('Skipping training — no labels available.')\n",
    "    history = None\n",
])

code([
    "# Plot training curves\n",
    "if history:\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
    "    \n",
    "    axes[0].plot(history['train_loss'], label='Train', color='steelblue')\n",
    "    axes[0].plot(history['val_loss'], label='Validation', color='darkorange')\n",
    "    axes[0].set_title('Loss Curves')\n",
    "    axes[0].set_xlabel('Epoch')\n",
    "    axes[0].set_ylabel('MSE Loss')\n",
    "    axes[0].legend()\n",
    "    \n",
    "    axes[1].plot(history['val_r'], color='darkgreen', marker='o')\n",
    "    axes[1].set_title('Validation Pearson r')\n",
    "    axes[1].set_xlabel('Epoch')\n",
    "    axes[1].set_ylabel('Pearson r')\n",
    "    axes[1].axhline(0.25, color='red', linestyle='--', label='Baseline ceiling')\n",
    "    axes[1].axhline(0.35, color='green', linestyle='--', label='Target')\n",
    "    axes[1].legend()\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(str(PROJECT_ROOT / 'data' / 'processed' / 'training_curves.png'), dpi=150)\n",
    "    plt.show()\n",
])

code([
    "# Null model sanity check\n",
    "# A model trained on shuffled labels must achieve r ≈ 0\n",
    "if HAS_LABELS:\n",
    "    print('Running null model sanity check (shuffled labels)...')\n",
    "    shuffled_labels = train_data['delta_yield_2y_bp'].values.copy()\n",
    "    np.random.shuffle(shuffled_labels)\n",
    "    \n",
    "    null_dataset = PolicyStanceDataset(\n",
    "        texts=train_data['text'].tolist()[:500],  # Subset for speed\n",
    "        labels=shuffled_labels[:500],\n",
    "        tokenizer=tokenizer,\n",
    "        max_length=MAX_LENGTH,\n",
    "    )\n",
    "    null_loader = DataLoader(null_dataset, batch_size=BATCH_SIZE, shuffle=True)\n",
    "    \n",
    "    # Quick 2-epoch train on shuffled\n",
    "    # (In practice, check that val r stays near 0)\n",
    "    print('If this yields |r| > 0.05, there is a data leakage bug!')\n",
    "    print('Null check defined — run separately if needed.')\n",
])


# ============================================================
# M6: EMBEDDING EXTRACTION & STANCE INDEX
# ============================================================
md([
    "---\n",
    "## Milestone 6: Embedding Extraction & Latent Stance Index\n",
    "\n",
    "After fine-tuning:\n",
    "1. Detach regression head\n",
    "2. Extract contextual embeddings e(x) ∈ ℝ^d from final transformer layer\n",
    "3. Fit PCA on TRAINING embeddings only\n",
    "4. Define stance score: s(x) = e(x)ᵀ · v₁ (first principal component)\n",
    "5. Validate PC1 aligns with hawkish-dovish dimension\n",
    "6. UMAP visualization\n",
])

code([
    "# Embedding extraction\n",
    "def extract_embeddings(model, dataloader, device):\n",
    "    \"\"\"Extract mean-pooled final-layer embeddings from the fine-tuned model.\"\"\"\n",
    "    model.eval()\n",
    "    all_embeddings = []\n",
    "    all_labels = []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for batch in tqdm(dataloader, desc='Extracting embeddings'):\n",
    "            input_ids = batch['input_ids'].to(device)\n",
    "            attention_mask = batch['attention_mask'].to(device)\n",
    "            \n",
    "            outputs = model.base_model(\n",
    "                input_ids=input_ids,\n",
    "                attention_mask=attention_mask,\n",
    "                output_hidden_states=True,\n",
    "            )\n",
    "            \n",
    "            # Mean pool over non-padded tokens\n",
    "            hidden = outputs.hidden_states[-1]\n",
    "            mask_exp = attention_mask.unsqueeze(-1).float()\n",
    "            mean_pooled = (hidden * mask_exp).sum(1) / mask_exp.sum(1)\n",
    "            \n",
    "            all_embeddings.append(mean_pooled.cpu().numpy())\n",
    "            if 'labels' in batch:\n",
    "                all_labels.extend(batch['labels'].numpy())\n",
    "    \n",
    "    embeddings = np.vstack(all_embeddings)\n",
    "    labels = np.array(all_labels) if all_labels else None\n",
    "    return embeddings, labels\n",
    "\n",
    "\n",
    "print('extract_embeddings() defined.')\n",
    "print(f'Output shape will be: (N_chunks, {hidden_size})')\n",
])

code([
    "# PCA and stance index construction\n",
    "from sklearn.decomposition import PCA\n",
    "\n",
    "def build_stance_index(train_embeddings, train_labels, all_embeddings):\n",
    "    \"\"\"\n",
    "    Build latent policy stance index via PCA.\n",
    "    PCA fitted on TRAINING data only (no leakage).\n",
    "    \n",
    "    Returns:\n",
    "        stance_scores: projection onto PC1 for all embeddings\n",
    "        pca: fitted PCA object\n",
    "    \"\"\"\n",
    "    # Fit PCA on training embeddings ONLY\n",
    "    pca = PCA(n_components=50)  # Keep top 50 components\n",
    "    pca.fit(train_embeddings)\n",
    "    \n",
    "    print(f'PCA fitted on training embeddings:')\n",
    "    print(f'  PC1 explains {pca.explained_variance_ratio_[0]*100:.1f}% of variance')\n",
    "    print(f'  Top 5 PCs explain {pca.explained_variance_ratio_[:5].sum()*100:.1f}%')\n",
    "    print(f'  Top 10 PCs explain {pca.explained_variance_ratio_[:10].sum()*100:.1f}%')\n",
    "    \n",
    "    # Project all embeddings\n",
    "    all_projected = pca.transform(all_embeddings)\n",
    "    stance_scores = all_projected[:, 0]  # PC1 = stance dimension\n",
    "    \n",
    "    # Validate: PC1 should correlate with yield labels\n",
    "    if train_labels is not None:\n",
    "        train_projected = pca.transform(train_embeddings)\n",
    "        r, p = stats.pearsonr(train_projected[:, 0], train_labels)\n",
    "        print(f'\\n  PC1 correlation with Δy₂ (train): r={r:.4f}, p={p:.2e}')\n",
    "        \n",
    "        # Flip sign if anti-correlated (so positive = hawkish)\n",
    "        if r < 0:\n",
    "            stance_scores = -stance_scores\n",
    "            print('  (Flipped PC1 sign so positive = hawkish)')\n",
    "    \n",
    "    return stance_scores, pca\n",
    "\n",
    "\n",
    "print('build_stance_index() defined.')\n",
])

code([
    "# UMAP visualization\n",
    "from umap import UMAP\n",
    "\n",
    "def visualize_stance_space(embeddings, labels, metadata_df, save_path=None):\n",
    "    \"\"\"2D UMAP visualization of the latent policy stance space.\"\"\"\n",
    "    \n",
    "    print('Running UMAP (n_components=2, metric=cosine)...')\n",
    "    reducer = UMAP(n_components=2, n_neighbors=15, min_dist=0.1, metric='cosine', random_state=SEED)\n",
    "    embedding_2d = reducer.fit_transform(embeddings)\n",
    "    \n",
    "    fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "    \n",
    "    # Color by yield label\n",
    "    if labels is not None:\n",
    "        scatter = axes[0].scatter(\n",
    "            embedding_2d[:, 0], embedding_2d[:, 1],\n",
    "            c=labels, cmap='RdBu_r', alpha=0.5, s=5,\n",
    "            vmin=-10, vmax=10\n",
    "        )\n",
    "        plt.colorbar(scatter, ax=axes[0], label='Δy₂ (bp)')\n",
    "    axes[0].set_title('Colored by Yield Change')\n",
    "    \n",
    "    # Color by year\n",
    "    years = metadata_df['year'].values\n",
    "    scatter = axes[1].scatter(\n",
    "        embedding_2d[:, 0], embedding_2d[:, 1],\n",
    "        c=years, cmap='viridis', alpha=0.5, s=5\n",
    "    )\n",
    "    plt.colorbar(scatter, ax=axes[1], label='Year')\n",
    "    axes[1].set_title('Colored by Year')\n",
    "    \n",
    "    # Color by central bank (top 5)\n",
    "    top5_cbs = metadata_df['central_bank'].value_counts().head(5).index\n",
    "    colors = ['red', 'blue', 'green', 'orange', 'purple']\n",
    "    for cb, color in zip(top5_cbs, colors):\n",
    "        mask = metadata_df['central_bank'] == cb\n",
    "        axes[2].scatter(\n",
    "            embedding_2d[mask, 0], embedding_2d[mask, 1],\n",
    "            c=color, alpha=0.4, s=5, label=cb[:20]\n",
    "        )\n",
    "    axes[2].legend(fontsize=8)\n",
    "    axes[2].set_title('Colored by Central Bank')\n",
    "    \n",
    "    for ax in axes:\n",
    "        ax.set_xlabel('UMAP-1')\n",
    "        ax.set_ylabel('UMAP-2')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    \n",
    "    return embedding_2d\n",
    "\n",
    "\n",
    "print('visualize_stance_space() defined.')\n",
])

code([
    "# Run embedding extraction and stance index (if model is trained)\n",
    "if HAS_LABELS and history:\n",
    "    # Load best checkpoint\n",
    "    ckpt_path = PROJECT_ROOT / 'models' / 'best_checkpoint' / 'model.pt'\n",
    "    model.load_state_dict(torch.load(ckpt_path))\n",
    "    print('Best checkpoint loaded.')\n",
    "    \n",
    "    # Extract embeddings for all splits\n",
    "    train_emb, train_lab = extract_embeddings(model, train_loader, device)\n",
    "    val_emb, val_lab = extract_embeddings(model, val_loader, device)\n",
    "    \n",
    "    print(f'Embeddings extracted:')\n",
    "    print(f'  Train: {train_emb.shape}')\n",
    "    print(f'  Val: {val_emb.shape}')\n",
    "    \n",
    "    # Build stance index\n",
    "    all_emb = np.vstack([train_emb, val_emb])\n",
    "    all_lab = np.concatenate([train_lab, val_lab]) if train_lab is not None else None\n",
    "    stance_scores, pca = build_stance_index(train_emb, train_lab, all_emb)\n",
    "    \n",
    "    # Save embeddings\n",
    "    emb_dir = PROJECT_ROOT / 'data' / 'processed'\n",
    "    np.save(emb_dir / 'embeddings_train.npy', train_emb)\n",
    "    np.save(emb_dir / 'embeddings_val.npy', val_emb)\n",
    "    np.save(emb_dir / 'stance_scores.npy', stance_scores)\n",
    "    print(f'\\nSaved embeddings and stance scores.')\n",
    "    \n",
    "    # Visualize\n",
    "    metadata = pd.concat([train_data[['year', 'central_bank']].reset_index(drop=True),\n",
    "                          val_data[['year', 'central_bank']].reset_index(drop=True)])\n",
    "    visualize_stance_space(\n",
    "        all_emb, all_lab, metadata,\n",
    "        save_path=str(PROJECT_ROOT / 'data' / 'processed' / 'umap_stance_space.png')\n",
    "    )\n",
    "else:\n",
    "    print('Model not yet trained. Run training first (requires market labels).')\n",
    "    print('Embedding extraction pipeline is fully defined and ready.')\n",
])


# ============================================================
# INTERPRETABILITY
# ============================================================
md([
    "---\n",
    "## Interpretability: Face Validity Check\n",
    "\n",
    "Examine the top-10 most hawkish and top-10 most dovish chunks by stance score.\n",
    "These must make economic sense (inflation → hawkish, slack → dovish).\n",
])

code([
    "# Face validity: inspect extreme chunks\n",
    "if HAS_LABELS and history:\n",
    "    # Combine chunks with stance scores\n",
    "    all_chunks_scored = pd.concat([train_data.reset_index(drop=True),\n",
    "                                   val_data.reset_index(drop=True)])\n",
    "    all_chunks_scored['stance_score'] = stance_scores\n",
    "    \n",
    "    print('TOP 10 MOST HAWKISH CHUNKS (highest stance score):')\n",
    "    print('=' * 60)\n",
    "    top_hawk = all_chunks_scored.nlargest(10, 'stance_score')\n",
    "    for _, row in top_hawk.iterrows():\n",
    "        print(f'\\n  Score: {row[\"stance_score\"]:.3f} | {row[\"central_bank\"]} | {row[\"date\"].date()}')\n",
    "        print(f'  \"{row[\"text\"][:200]}...\"')\n",
    "    \n",
    "    print('\\n\\nTOP 10 MOST DOVISH CHUNKS (lowest stance score):')\n",
    "    print('=' * 60)\n",
    "    top_dove = all_chunks_scored.nsmallest(10, 'stance_score')\n",
    "    for _, row in top_dove.iterrows():\n",
    "        print(f'\\n  Score: {row[\"stance_score\"]:.3f} | {row[\"central_bank\"]} | {row[\"date\"].date()}')\n",
    "        print(f'  \"{row[\"text\"][:200]}...\"')\n",
    "else:\n",
    "    print('Interpretability analysis requires trained model.')\n",
])

# ============================================================
# NEXT STEPS
# ============================================================
md([
    "---\n",
    "## Summary & Next Steps\n",
    "\n",
    "### Phase 3 Complete:\n",
    "- [x] Temporal train/val/test split (2005-2018 / 2019-2020 / 2021+)\n",
    "- [x] PolicyStanceRegressor (LLM + LoRA + regression head)\n",
    "- [x] Training loop with early stopping & overfitting detection\n",
    "- [x] Null model sanity check framework\n",
    "- [x] Embedding extraction pipeline\n",
    "- [x] PCA-based stance index (PC1 = hawkish-dovish)\n",
    "- [x] UMAP visualization\n",
    "- [x] Face validity interpretability\n",
    "\n",
    "### Phase 4 — Robustness & OOS Testing:\n",
    "- [ ] Walk-forward cross-validation\n",
    "- [ ] Ablation studies (LoRA rank, model size, document type)\n",
    "- [ ] Economic significance tests\n",
    "- [ ] Placebo tests\n",
])


# ============================================================
# BUILD NOTEBOOK
# ============================================================
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

nb_path.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
print(f"Phase 3 notebook written: {nb_path}")
print(f"Total cells: {len(cells)}")
